name: pushtag

on:
  push:
    tags:
      - '**'

jobs:
  test:
    name: 'Testing 1-2-3: tag push'
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Triggered!
        run: echo 'Workflow triggered!'
